name: deploy on push
on:
  push:
    branches:
      - main  # 只在 main 分支推送时，部署到开发服务器
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4

      - name: Set target directory permissions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html
            sudo chown -R ubuntu:ubuntu /var/www/html
            sudo chmod -R 755 /var/www/html

      - name: Copy files to dev server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            index.html
            Eloisa-photo.jpg
          target: "/var/www/html"
