name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # 用 SSH 命令直接上传文件，不用 SCP
      - name: Deploy files via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 先授权
            sudo mkdir -p /var/www/html
            sudo chown -R ubuntu:ubuntu /var/www/html
            sudo chmod -R 755 /var/www/html
            
            # 直接从仓库拉取文件（这里用 raw.githubusercontent.com 的链接）
            cd /var/www/html
            curl -O https://raw.githubusercontent.com/Eloisa-virgo/Lab7_deve/main/index.html
            curl -O https://raw.githubusercontent.com/Eloisa-virgo/Lab7_deve/main/Eloisa-photo.jpg
            
            # 重启 Nginx 让它生效
            sudo systemctl restart nginx
